create:
  path: /create
  controller: App\UserInterface\Controller\ProductController::create
  methods: ['POST']

index:
  path: /index
  controller: App\UserInterface\Controller\ProductController::index
  methods: ['GET']
